### ISSUE TITLE
How to get the model files from a .dwg file

### ISSUE THREAD

**Issue by d-bose** [ghemingway/cad.js#35]
Hi, I have a .dwg file. How can I get the json files required by cad.js from it. I tried to convert the .dwg files using autocad to json but none matches with the format you guys have. So what should I do in this situation. I have a .dwg file & want to load this model in this tool (cad js)

**Comment by ghemingway** [comment]
Right now the tool only supports models in the STEP file format.  Sorry.  You may be able to get AutoCAD (of whatever tool generated the .dwg file) to export a .stp instead.

**Comment by d-bose** [comment]
Thanks for your reply. From the code it seem that it takes json file (index.json, batch.json,annotation.json, etc..) as input. I however, could not find a way to load a .stp file. Can you please help me understand how I can load a .stp file into cad.js ? Thanks...

**Comment by losthua** [comment]
Hi, I'm doing a test like this.Do you have access to the.stp file?

**Comment by imgrammy** [comment]
@losthua have you done anything with it?
